#!/usr/bin/env python3

# start_master_instance.py
import subprocess
import time, os, sys
from os import environ as env
from novaclient import client
from keystoneauth1 import loading, session

# PUBLIC_KEY_NAME: name of public key used found on SSC
# PRIVATE_KEY_PATH: private key used to connect to master VM
if len(sys.argv) != 3 or sys.argv[1] == '--help':
    print("Usage: python3 start_master_instance.py <PUBLIC_KEY_NAME> <PRIVATE_KEY_PATH>")
    exit(1)

# --- Config ---
KEY_NAME        = sys.argv[1]
KEY_PATH        = sys.argv[2]
FLAVOR_NAME     = 'ssc.medium'
PRIVATE_NET     = 'UPPMAX 2026/1-24 Internal IPv4 Network'
IMAGE_NAME      = 'Ubuntu 22.04 - 2024.01.15'
INSTANCE_NAME   = 'group16-master'
CLOUD_CFG_PATH  = 'cloud-cfg-master.txt'

# --- Auth ---
loader = loading.get_plugin_loader('password')
auth = loader.load_from_options(
    auth_url=env['OS_AUTH_URL'],
    username=env['OS_USERNAME'],
    password=env['OS_PASSWORD'],
    project_name=env['OS_PROJECT_NAME'],
    project_domain_id=env['OS_PROJECT_DOMAIN_ID'],
    project_id=env['OS_PROJECT_ID'],
    user_domain_name=env['OS_USER_DOMAIN_NAME'],
)
sess = session.Session(auth=auth)
nova = client.Client('2.1', session=sess)
print("Authenticated.")

# --- Resolve resources ---
image    = nova.glance.find_image(IMAGE_NAME)
flavor   = nova.flavors.find(name=FLAVOR_NAME)
net      = nova.neutron.find_network(PRIVATE_NET)
nics     = [{'net-id': net.id}]

with open(CLOUD_CFG_PATH) as f:
    userdata = f.read()

# --- Create instance ---
print(f"Creating instance '{INSTANCE_NAME}'...")
instance = nova.servers.create(
    name=INSTANCE_NAME,
    image=image,
    key_name=KEY_NAME,
    flavor=flavor,
    userdata=userdata,
    nics=nics,
    security_groups=['default'],
)

# --- Wait for ACTIVE ---
print("Waiting for instance to become ACTIVE...")
while True:
    instance = nova.servers.get(instance.id)
    if instance.status == 'ACTIVE':
        print("Instance is ACTIVE.")
        break
    elif instance.status == 'ERROR':
        sys.exit("Instance entered ERROR state. Aborting.")
    print(f"  Status: {instance.status}, waiting 5s...")
    time.sleep(5)

# --- Attach manually floating IP ---
FLOATING_IP = input("Provide assigned floating IP: ")

# --- Wait for SSH to be ready ---
print("Waiting for SSH to become available...")
import socket
for _ in range(30):
    try:
        sock = socket.create_connection((FLOATING_IP, 22), timeout=5)
        sock.close()
        print("  SSH is up.")
        break
    except (socket.timeout, ConnectionRefusedError, OSError):
        print("  Not ready yet, waiting 10s...")
        time.sleep(10)
else:
    print("Warning: SSH did not become available in time. You may need to wait a bit.")

# --- Retrieve the cluster public key (generated by cloud-init) ---
print("Waiting for cloud-init to finish...")
max_attempts=30
success = False
for attempt in range(1, max_attempts + 1):
    result = subprocess.run([
        "ssh",
        "-i", KEY_PATH,
        "-o", "StrictHostKeyChecking=no",
        "-o", "BatchMode=yes",
        f"ubuntu@{FLOATING_IP}",
        "cloud-init status --wait"
    ], capture_output=True, text=True)

    stdout = result.stdout.strip()
    stderr = result.stderr.strip()

    if result.returncode == 0:
        print("cloud-init finished successfully.")
        if stdout:
            print(stdout)
        success = True
        break

    print(f"cloud-init status failed/crashed on attempt {attempt}/{max_attempts}.")
    if stdout:
        print("STDOUT:")
        print(stdout)
    if stderr:
        print("STDERR:")
        print(stderr)

    print(f"Retrying in 10s...")
    time.sleep(10)

if not success:
    print("Warning: cloud-init did not finish successfully within the retry limit.")
    exit(1)

result = subprocess.run([
    'ssh', '-i', KEY_PATH,
    '-o', 'StrictHostKeyChecking=accept-new',
    f'ubuntu@{FLOATING_IP}',
    'cat /home/ubuntu/.ssh/cluster_key.pub'
], capture_output=True, text=True)

cluster_pubkey = result.stdout.strip()
if cluster_pubkey:
    print(f"Cluster public key retrieved.")
else:
    print("Warning: could not retrieve cluster key.")
    print(f"  Retrieve manually: ssh -i {KEY_PATH} ubuntu@{FLOATING_IP} cat /home/ubuntu/.ssh/cluster_key.pub")

# --- Save info for later use ---
with open('master_info.txt', 'w') as f:
    f.write(f"MASTER_IP={FLOATING_IP}\n")
    f.write(f"CLUSTER_PUBKEY={cluster_pubkey}\n")

print(f"\nDone. Master IP: {FLOATING_IP}")
print("Info saved to master_info.txt")
